// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_tokens
SET updated_at = $2, revoked_at = $3
WHERE token = $1
`

type UpdateRefreshTokenParams struct {
	Token     string       `json:"token"`
	UpdatedAt time.Time    `json:"updated_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.Token, arg.UpdatedAt, arg.RevokedAt)
	return err
}
