// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upgrade_user_membership.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserMembership = `-- name: UpgradeUserMembership :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) UpgradeUserMembership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeUserMembership, id)
	return err
}
